import { toISODate, addDays, startOfWeek } from './utils/date.js';

export const DEMO_PROJECT_ID = 'demo-room-bloom';

export function buildDemoData() {
  const project = {
    id: DEMO_PROJECT_ID,
    name: 'Room Bloom',
    color: '#4A9990',
    isDemo: true,
  };

  const weekStart = startOfWeek(new Date());
  const d = (offset) => toISODate(addDays(weekStart, offset));

  const posts = [
    {
      id: 'demo-post-1',
      projectId: project.id,
      topic: 'Обзор квартиры: свет и планировка',
      date: d(0),
      time: '10:00',
      platform: 'Instagram',
      format: 'Reels',
      status: 'Идея',
      text: 'Черновой сценарий обзора: показать вход, гостиную, окна. Демонстрационный текст — заменить на реальный.',
      materialsLink: '',
      notes: 'Демонстрационная запись, можно удалить.',
      rubric: 'Обзоры',
      goal: 'Показать формат подачи объектов',
      audience: '',
      cta: '',
      script: '',
      coverText: '',
      checklist: [],
      linkedGroupId: null,
      isIdea: false,
      isArchived: false,
      isDemo: true,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      id: 'demo-post-2',
      projectId: project.id,
      topic: 'Подборка: районы для переезда',
      date: d(1),
      time: '13:30',
      platform: 'Telegram',
      format: 'Пост',
      status: 'В работе',
      text: 'Пример текста-подборки районов с демонстрационными пунктами (без реальных цен и характеристик).',
      materialsLink: '',
      notes: '',
      rubric: 'Подборки',
      goal: '',
      audience: '',
      cta: '',
      script: '',
      coverText: '',
      checklist: [
        { id: 'c1', text: 'Собрать фото', done: true },
        { id: 'c2', text: 'Проверить факты', done: false },
      ],
      linkedGroupId: null,
      isIdea: false,
      isArchived: false,
      isDemo: true,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      id: 'demo-post-3',
      projectId: project.id,
      topic: 'Экспертный Reels: на что смотреть при выборе квартиры',
      date: d(3),
      time: '18:00',
      platform: 'Instagram',
      format: 'Reels',
      status: 'На согласовании',
      text: 'Демонстрационный сценарий экспертного видео. Заменить примерным текстом на реальный.',
      materialsLink: '',
      notes: '',
      rubric: 'Экспертиза',
      goal: 'Повысить доверие аудитории',
      audience: '',
      cta: 'Написать в директ',
      script: '1. Приветствие\n2. Три совета\n3. Призыв к действию',
      coverText: 'На что смотреть при выборе?',
      checklist: [],
      linkedGroupId: null,
      isIdea: false,
      isArchived: false,
      isDemo: true,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      id: 'demo-post-4',
      projectId: project.id,
      topic: 'Stories с опросом про формат ремонта',
      date: d(4),
      time: '09:00',
      platform: 'Instagram',
      format: 'Stories',
      status: 'Готово',
      text: 'Демонстрационный вопрос для опроса в Stories.',
      materialsLink: '',
      notes: 'Готово к публикации, пример.',
      rubric: '',
      goal: '',
      audience: '',
      cta: '',
      script: '',
      coverText: '',
      checklist: [],
      linkedGroupId: null,
      isIdea: false,
      isArchived: false,
      isDemo: true,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  ];

  return { project, posts };
}
